In [1]:
import pandas as pd

In [12]:
zx_list = pd.read_excel("中信证券产品.xlsx", header=None)[0].tolist()

In [13]:
zx_list

['暨阳1号',
 '暨阳3号',
 '汇金3号',
 '高升3号',
 '高升2号',
 '高升5号',
 '高升6号',
 '高升7号',
 '高升8号',
 '兴盛1号',
 '绿洲4号',
 '绿洲5号',
 '飞龙7号']

In [16]:
zcz = pd.ExcelFile("注册制.xlsx")
zcz.sheet_names

['瑞丰新材',
 '仲景食品',
 '汇创达',
 '康平科技',
 '狄耐克',
 '科翔股份',
 '兰剑智能',
 '艾力斯',
 '中控技术',
 '会通股份',
 '金达莱',
 '利扬芯片',
 '豪森股份']

In [62]:
hss = pd.DataFrame(index=zcz.sheet_names, columns=["中信产品", "其他"])

In [23]:
pd.read_excel("注册制.xlsx", sheet_name="艾力斯", header=1)

,序号,证券账户,数量,均价,金额,发行价,缴款金额,收益,涨幅,Unnamed: 9,539552.9996300942
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,699294.000302
1,黄总产品合计,NaN,159741,41.528890,6.633866e+06,22.73,3.630913e+06,3.002953e+06,0.827052,NaN,NaN
2,其他合计,NaN,539553,41.463456,2.237173e+07,22.73,1.226404e+07,1.010769e+07,0.824173,NaN,NaN
3,合计,NaN,699294,41.478403,2.900560e+07,22.73,1.589495e+07,1.311065e+07,0.824831,NaN,NaN
4,1,和谐1号,4353,41.879600,1.823019e+05,22.73,9.894369e+04,8.335821e+04,0.842481,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
179,176,巡洋1号,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,177,合力1号,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,178,合力2号,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,179,合力3号,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,180,龙凤8号,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df  = pd.read_excel("注册制.xlsx", sheet_name="瑞丰新材", header=1)

In [35]:
df["证券账户"]

0        NaN
1        NaN
2        NaN
3        NaN
4       和谐2号
       ...
128     飞龙7号
129    起航15号
130     巡洋1号
131     合力3号
132     龙凤8号
Name: 证券账户, Length: 133, dtype: object

In [71]:
for sheet in zcz.sheet_names:
    df  = pd.read_excel("注册制.xlsx", sheet_name=sheet, header=1)
    for item in zx_list:
        je = 0
        sl = 0
        if item in df["证券账户"].tolist():
            idx = df[df["证券账户"] == item].index[0]
            je += df["金额"][idx]
            sl += df["数量"][idx]
    hss["中信产品"][sheet] = je / sl
    hss["其他"][sheet] = (df["金额"][2] - je) / (df["数量"][2] - sl)

In [73]:
hss.to_excel("均价对比.xlsx")

In [67]:
hss["中信产品"]["瑞丰新材"] = zx_jj

In [74]:
hss

         中信产品       其他
瑞丰新材  84.3521  83.4504
仲景食品  120.523  120.146
汇创达   91.1286  90.3779
康平科技   59.808  60.3903
狄耐克    73.638  74.2252
科翔股份   58.945  58.5575
兰剑智能   73.633  73.4567
艾力斯   41.2019  41.4654
中控技术  109.037  108.789
会通股份  35.6874  34.2578
金达莱   44.2545  44.0336
利扬芯片    67.34  66.9255
豪森股份    60.19  60.1738